### ISSUE TITLE
Loss of changes with one client connected

### ISSUE THREAD

**Issue by Jhoysbou** [a-la-fois/a-la-fois#92]
While docHandler actor is relocating we can lose some changes if only one client is connected to this actor

**Comment by Jhoysbou** [comment]
I'm thinking about adding a result message for actor's `applyDiff` method. In result message, we can ask a client to start a synchronization.

But I suggest to not check if sync is needed every method call, instead we can create a timer that runs every n seconds and checks for sync. If the sync is needed, just switch a flag and then on a new `applyDiff` we return a sync request. 

@evilfant What is your opinion on this?

**Comment by evilfant** [comment]
> I'm thinking about adding a result message for actor's `applyDiff` method. In result message, we can ask a client to start a synchronization.
> 
> But I suggest to not check if sync is needed every method call, instead we can create a timer that runs every n seconds and checks for sync. If the sync is needed, just switch a flag and then on a new `applyDiff` we return a sync request.
> 
> @evilfant What is your opinion on this?

Nice idea

Why not return the sync request after the first document desync?
To avoid multiple sync requests to the same user we can add "debounce"
